word_list = [
    "book", "tree", "fish", "game", "code", "lamp", "milk", "door", "rain", "snow",
    "bird", "cake", "moon", "star", "ship", "apple", "chair", "plant", "mouse", "bread",
    "banana", "orange", "grapes", "mango", "pineapple", "watermelon", "strawberry", "blueberry",
    "computer", "keyboard", "monitor", "printer", "internet", "network", "server",
    "python", "java", "javascript", "compiler", "software", "hardware", "database",
    "science", "physics", "chemistry", "biology", "mathematics", "algebra", "geometry",
    "history", "geography", "school", "college", "teacher", "student", "library",
    "football", "cricket", "tennis", "hockey", "badminton", "volleyball",
    "elephant", "giraffe", "kangaroo", "penguin", "dolphin", "butterfly",
    "alligator", "crocodile", "chimpanzee", "rhinoceros",
    "mountain", "river", "forest", "desert", "ocean", "island",
    "sunshine", "rainbow", "thunder", "lightning", "calendar", "holiday", "festival", "birthday",
    "adventure", "journey", "treasure", "diamond", "castle", "village",
    "airport", "station", "hospital", "pharmacy", "restaurant",
    "sandwich", "chocolate", "icecream", "umbrella", "backpack",
    "bicycle", "airplane", "helicopter", "submarine",
    "astronaut", "satellite", "galaxy", "planet", "universe",
    "algorithm", "programming", "engineering", "communication",
    "development", "framework", "application", "encryption",
    "debugging", "authentication", "configuration",
    "implementation", "cybersecurity", "microprocessor",
    "virtualization", "cryptography", "international",
    "responsibility", "architecture", "encyclopedia",
    "transportation", "extraordinary"
]